# Generated by Django 5.0.7 on 2024-09-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_metadata_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
