# Generated by Django 5.0.7 on 2024-09-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_short_description_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
