# Generated by Django 5.0.7 on 2024-09-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
