# Generated by Django 5.0.7 on 2024-09-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_tags',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='api.tag'),
        ),
    ]
